# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

triplets_to_pairs <- function(triplets) {
    .Call('_gagarin_triplets_to_pairs', PACKAGE = 'gagarin', triplets)
}

dgCMat_to_pairs_cpp <- function(ivec, pvec, xvec) {
    .Call('_gagarin_dgCMat_to_pairs_cpp', PACKAGE = 'gagarin', ivec, pvec, xvec)
}

